[project]
name = "proyecto-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "earthengine-api>=1.7.25",
    "gcloud>=0.18.3",
    "gcsfs>=2026.5.0",
    "google-cloud-storage>=3.10.1",
    "huggingface-hub>=1.14.0",
    "kaggle>=2.1.2",
    "pypdf>=6.11.0",
    "python-dotenv>=1.2.2",
    "rioxarray>=0.22.0",
    "tqdm>=4.67.3",
    "xarray>=2026.4.0",
    "xee>=0.1.0",
    "zarr>=3.2.1",
]
