[project]
name = "proyecto-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "earthengine-api>=1.7.25",
    "gcloud>=0.18.3",
    "gcsfs>=2026.5.0",
    "google-cloud-storage>=3.10.1",
    "huggingface-hub>=1.14.0",
    "ipykernel>=7.2.0",
    "kaggle>=2.1.2",
    "kagglehub>=1.0.1",
    "matplotlib>=3.10.9",
    "nbconvert>=7.17.1",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pyarrow>=24.0.0",
    "pypdf>=6.11.0",
    "python-dotenv>=1.2.2",
    "rioxarray>=0.22.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "tqdm>=4.67.3",
    "xarray>=2026.4.0",
    "xee>=0.1.0",
    "zarr>=3.2.1",
]
